# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('default_from', models.CharField(blank=True, help_text='Optional. From in code passed into send takes precedence. DEFAULT_FROM used if available.', max_length=128)),
                ('html', models.TextField()),
                ('plain_text', models.TextField(blank=True, help_text='Optional. If blank generated from html')),
            ],
        ),
    ]
